// scripts/figma-to-arco/theme-generator.ts

import * as fs from 'node:fs';
import * as path from 'node:path';
import type { ResolvedToken, TokenEntry, MappingConfig } from './types';

const THEME_SELECTOR: Record<string, string> = {
  light: '[data-arco-theme="light"]',
  dark: '[data-arco-theme="dark"]',
};

function ensureDir(dir: string): void {
  fs.mkdirSync(dir, { recursive: true });
}

// ── CSS 输出 ──

function generateCSS(tokens: ResolvedToken[]): string {
  // 收集所有 theme 名称
  const themes = new Set<string>();
  for (const t of tokens) {
    for (const theme of Object.keys(t.valuesByTheme)) {
      themes.add(theme);
    }
  }

  const lines: string[] = ['/* Auto-generated by figma-to-arco */', ''];

  for (const theme of themes) {
    const selector = THEME_SELECTOR[theme] ?? `[data-arco-theme="${theme}"]`;
    lines.push(`${selector} {`);

    for (const token of tokens) {
      const val = token.valuesByTheme[theme];
      if (val !== undefined) {
        lines.push(`  --${token.arcoName}: ${val};`);
      }
    }

    lines.push('}', '');
  }

  return lines.join('\n');
}

function generateSingleThemeCSS(tokens: ResolvedToken[], theme: string): string {
  const lines: string[] = [
    `/* Auto-generated by figma-to-arco — ${theme} theme */`,
    '',
    ':root {',
  ];

  for (const token of tokens) {
    const val = token.valuesByTheme[theme];
    if (val !== undefined) {
      lines.push(`  --${token.arcoName}: ${val};`);
    }
  }

  lines.push('}', '');
  return lines.join('\n');
}

// ── Less 输出 ──

function generateGlobalLess(tokens: ResolvedToken[]): string {
  const globalTokens = tokens.filter(t => t.component === null);
  const lines: string[] = [
    '// Auto-generated by figma-to-arco — global tokens',
    '',
  ];

  for (const token of globalTokens) {
    // Less 变量用 @ 前缀
    const val = token.valuesByTheme['light'] ?? Object.values(token.valuesByTheme)[0];
    lines.push(`@${token.arcoName}: ${val};`);
  }

  return lines.join('\n');
}

function generateComponentLess(tokens: ResolvedToken[]): Map<string, string> {
  const componentTokens = tokens.filter(t => t.component !== null);
  const grouped = new Map<string, ResolvedToken[]>();

  for (const token of componentTokens) {
    const comp = token.component!.replace(/[/\\]/g, '-');
    if (!grouped.has(comp)) grouped.set(comp, []);
    grouped.get(comp)!.push(token);
  }

  const files = new Map<string, string>();
  for (const [comp, compTokens] of grouped) {
    const lines: string[] = [
      `// Auto-generated by figma-to-arco — ${comp} tokens`,
      '',
    ];
    for (const token of compTokens) {
      const val = token.valuesByTheme['light'] ?? Object.values(token.valuesByTheme)[0];
      lines.push(`@${token.arcoName}: ${val};`);
    }
    files.set(comp, lines.join('\n'));
  }

  return files;
}

// ── JSON 输出 ──

function generateJSON(tokens: ResolvedToken[]): string {
  const result: Record<string, Record<string, string>> = {};

  for (const token of tokens) {
    result[token.arcoName] = token.valuesByTheme;
  }

  return JSON.stringify(result, null, 2);
}

// ── README ──

function generateREADME(packageName: string): string {
  return `# ${packageName}

Auto-generated Arco Design theme package from Figma design tokens.

## Usage

\`\`\`tsx
import '${packageName}/css/theme.css';
// Arco components auto-respond to data-arco-theme attribute
\`\`\`

## Files

| Path | Description |
|------|-------------|
| \`css/theme.css\` | CSS variables grouped by theme mode |
| \`less/global.less\` | Global Less variables |
| \`less/component/\` | Component-level Less variables |
| \`tokens/tokens.json\` | Raw token data for programmatic use |
`;
}

// ── package.json ──

function generatePackageJson(packageName: string): string {
  return JSON.stringify(
    {
      name: packageName,
      version: '1.0.0',
      description: `Arco Design theme: ${packageName} (auto-generated from Figma)`,
      main: 'css/theme.css',
      files: ['css/', 'less/', 'tokens/'],
      license: 'UNLICENSED',
    },
    null,
    2
  );
}

// ── 未匹配 token 报告 ──

function reportUnmapped(unmapped: TokenEntry[], outputDir: string): void {
  if (unmapped.length === 0) return;

  const lines: string[] = [
    `# 未匹配 Token 报告`,
    '',
    `以下 ${unmapped.length} 个 Figma token 未被映射到 Arco 名称。`,
    '请在 arco-theme-mapping.yml 的 `tokens` 段中添加精确映射后重新运行。',
    '',
    '| Figma 名称 | Collection | 类型 | 建议 Arco 名称 |',
    '|-----------|-----------|------|---------------|',
  ];

  for (const entry of unmapped) {
    const suggested = entry.figmaPath && entry.figmaPath.length > 0
      ? entry.figmaPath.map(p => p.toLowerCase().replace(/\s+/g, '-')).join('-')
      : entry.figmaName.toLowerCase().replace(/\s+/g, '-');
    lines.push(
      `| \`${entry.figmaName}\` | ${entry.collectionName} | ${entry.type} | \`${suggested}\` |`
    );
  }

  const reportPath = path.join(outputDir, 'UNMAPPED-TOKENS.md');
  fs.writeFileSync(reportPath, lines.join('\n'), 'utf-8');
  console.log(`\n⚠  ${unmapped.length} 个 token 未映射，报告已输出到 ${reportPath}`);
}

// ── 公共接口 ──

export function generateThemePackage(
  tokens: ResolvedToken[],
  unmapped: TokenEntry[],
  config: MappingConfig
): void {
  const { packageName, dir } = config.output;
  if (!dir) throw new Error('config.output.dir is required');
  const outRoot = path.resolve(dir);

  console.log(`\n📝 生成主题包到 ${outRoot}...`);

  // 清理旧输出
  if (fs.existsSync(outRoot)) {
    fs.rmSync(outRoot, { recursive: true });
  }

  // CSS
  ensureDir(path.join(outRoot, 'css'));
  const cssContent = generateCSS(tokens);
  fs.writeFileSync(path.join(outRoot, 'css', 'theme.css'), cssContent, 'utf-8');
  console.log('   ✅ css/theme.css');

  for (const theme of Object.keys(THEME_SELECTOR)) {
    const hasTheme = tokens.some(t => t.valuesByTheme[theme] !== undefined);
    if (hasTheme) {
      const singleCSS = generateSingleThemeCSS(tokens, theme);
      fs.writeFileSync(path.join(outRoot, 'css', `theme-${theme}.css`), singleCSS, 'utf-8');
      console.log(`   ✅ css/theme-${theme}.css`);
    }
  }

  // Less
  ensureDir(path.join(outRoot, 'less'));
  const lessGlobal = generateGlobalLess(tokens);
  fs.writeFileSync(path.join(outRoot, 'less', 'global.less'), lessGlobal, 'utf-8');
  console.log('   ✅ less/global.less');

  const componentLess = generateComponentLess(tokens);
  if (componentLess.size > 0) {
    ensureDir(path.join(outRoot, 'less', 'component'));
    for (const [comp, content] of componentLess) {
      fs.writeFileSync(path.join(outRoot, 'less', 'component', `${comp}.less`), content, 'utf-8');
      console.log(`   ✅ less/component/${comp}.less`);
    }
  }

  // JSON
  ensureDir(path.join(outRoot, 'tokens'));
  const jsonContent = generateJSON(tokens);
  fs.writeFileSync(path.join(outRoot, 'tokens', 'tokens.json'), jsonContent, 'utf-8');
  console.log('   ✅ tokens/tokens.json');

  // README + package.json
  fs.writeFileSync(path.join(outRoot, 'README.md'), generateREADME(packageName), 'utf-8');
  fs.writeFileSync(path.join(outRoot, 'package.json'), generatePackageJson(packageName), 'utf-8');
  console.log('   ✅ README.md + package.json');

  // 未匹配 token 报告
  reportUnmapped(unmapped, outRoot);

  console.log(`\n🎉 主题包生成完成: ${outRoot}/`);
}
