import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  guide: [{ type: 'autogenerated', dirName: 'guide' }],
  components: [{ type: 'autogenerated', dirName: 'components' }],
  businessComponents: [{ type: 'autogenerated', dirName: 'business-components' }],
  pageTemplates: [{ type: 'autogenerated', dirName: 'page-templates' }],
};

export default sidebars;
