// CJS shim — re-exports icons from @arco-design/web-vue/es/icon.
// This is the `require` target in package.json "exports". The `import` condition
// points at dist/icon.mjs (generated by scripts/build-shims.mjs) instead: a real ESM
// re-export using a fully-specified path is required there because Vite dev serves
// linked workspace packages without prebundling, and this CJS file's dynamic
// Object.defineProperty getters aren't statically analyzable for named-export
// interop in that unbundled path.
const icon = require('@arco-design/web-vue/es/icon');

for (const key of Object.keys(icon)) {
  if (key !== 'default' && !Object.prototype.hasOwnProperty.call(exports, key)) {
    Object.defineProperty(exports, key, {
      enumerable: true,
      get: () => icon[key],
    });
  }
}
